import AdminNavbar from "@/components/adminNavbar";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AdminLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="w-full ">
      <AdminNavbar />
      <div>{children}</div>
    </div>
  );
}
